version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - './mongodb:/data/db'
    ports:
      - 27017:27017
  parse:
    image: parseplatform/parse-server:latest
    environment:
      - PARSE_SERVER_APPLICATION_ID=APPLICATION_ID
      - PARSE_SERVER_MASTER_KEY=MASTER_KEY
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/parse
      - PARSE_SERVER_MOUNT_PATH=/parse
    ports:
      - 1337:1337
    links:
      - mongo
  parse-dashboard:
    image: parseplatform/parse-dashboard:latest
    ports:
      - 4040:4040
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_SERVER_URL=/api
      - PARSE_DASHBOARD_MASTER_KEY=MASTER_KEY
      - PARSE_DASHBOARD_APP_ID=APPLICATION_ID
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=admin
      - MOUNT_PATH=/dashboard/
    links:
      - parse
  portainer:
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - './nginx:/etc/nginx/sites-enabled'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './localhost.cert:/etc/nginx/ssl/localhost.cert'
      - './localhost.key:/etc/nginx/ssl/localhost.key'
    links:
      - parse-dashboard
      - parse
      - portainer
volumes:
  portainer_data: